import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedTUHORARIOWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedBarraWidget3.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedMenuWidget6.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax4widget/generated/GeneratedHorarioteatencion900am300pmHorariodetrabajo700am300pm20.dart';

/* Frame iPhone 11 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedMenuWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedBarraWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 71.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 47.0,
                child: GeneratedTUHORARIOWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 186.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 229.0,
                child:
                    GeneratedHorarioteatencion900am300pmHorariodetrabajo700am300pm20(),
              )
            ]),
      ),
    ));
  }
}
