import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedHandsChickenWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedPOLLOLOKOWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedENTRARWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedBienvenidoWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedRestauranteWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax1widget/generated/GeneratedOpenDoodlesCoffeeWidget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 595.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -191.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedOpenDoodlesCoffeeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 422.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 59.0,
                child: GeneratedBienvenidoWidget(),
              ),
              Positioned(
                left: 196.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 111.0,
                child: GeneratedHandsChickenWidget(),
              ),
              Positioned(
                left: -36.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 66.0,
                child: GeneratedRestauranteWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 48.0,
                child: GeneratedPOLLOLOKOWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 59.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 125.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 37.0,
                child: GeneratedENTRARWidget(),
              )
            ]),
      ),
    ));
  }
}
