import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedVermasofertasWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedBarraWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax2widget/generated/GeneratedVisitanosennuestranuevasucursalytendrasunaoferta2x1enel.dart';

/* Frame iPhone 11 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedBarraWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 276.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 116.0,
                child:
                    GeneratedVisitanosennuestranuevasucursalytendrasunaoferta2x1enel(),
              ),
              Positioned(
                left: 59.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 68.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 98.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 35.0,
                child: GeneratedVermasofertasWidget(),
              )
            ]),
      ),
    ));
  }
}
