import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedMenuWidget10.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedSalarioWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedTurnoWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedEmpleadodelmesRepartidorexpresPollitobienhechoEchalelam.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedBarraWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedSucursalWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedLopezMateosWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedMatutinoWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedLuisMartinezLopezWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedMedallasWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax5widget/generated/GeneratedRectangle10Widget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedMenuWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedBarraWidget4(),
              ),
              Positioned(
                left: 133.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 149.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 41.0,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 41.0,
                child: GeneratedSalarioWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 41.0,
                child: GeneratedSucursalWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 41.0,
                child: GeneratedTurnoWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 34.0,
                child: GeneratedLuisMartinezLopezWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 37.0,
                child: GeneratedMatutinoWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 37.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 37.0,
                child: GeneratedMedallasWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 45.0,
                child:
                    GeneratedEmpleadodelmesRepartidorexpresPollitobienhechoEchalelam(),
              ),
              Positioned(
                left: 43.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 34.0,
                child: GeneratedLopezMateosWidget(),
              )
            ]),
      ),
    ));
  }
}
