import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedComidaWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedComidaWidget3.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedMenuWidget2.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedBarraWidget2.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedComidaWidget.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedComidaWidget1.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatediphone11promax3widget/generated/GeneratedComidaWidget2.dart';

/* Frame iPhone 11 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedMenuWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedBarraWidget2(),
              ),
              Positioned(
                left: 11.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 120.0,
                child: GeneratedComidaWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 120.0,
                child: GeneratedComidaWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 120.0,
                child: GeneratedComidaWidget2(),
              ),
              Positioned(
                left: 19.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 120.0,
                child: GeneratedComidaWidget3(),
              ),
              Positioned(
                left: 19.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 120.0,
                child: GeneratedComidaWidget4(),
              )
            ]),
      ),
    ));
  }
}
