import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedMenuWidget9.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedPeoplecircleoutlineWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedHomeWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedInicioWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedHorarioWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedPerfilWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedFastfoodWidget4.dart';
import 'package:flutterapp/proyecto_20final_20especialidadapp/generatedmenuwidget8/generated/GeneratedAlarmWidget4.dart';

/* Component Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle4Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.11835748792270531;

                final double height =
                    constraints.maxHeight * 0.6081081081081081;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09903381642512077,
                      y: constraints.maxHeight * 0.05405405405405406,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedHomeWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.1473429951690821;

                final double height =
                    constraints.maxHeight * 0.6486486486486487;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3285024154589372,
                      y: constraints.maxHeight * 0.013513513513513514,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedFastfoodWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.1280193236714976;

                final double height =
                    constraints.maxHeight * 0.6351351351351351;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.572463768115942,
                      y: constraints.maxHeight * 0.02702702702702703,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedAlarmWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.17632850241545894;

                final double height =
                    constraints.maxHeight * 0.2702702702702703;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.10869565217391304,
                      y: constraints.maxHeight * 0.6621621621621622,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInicioWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.17632850241545894;

                final double height =
                    constraints.maxHeight * 0.2702702702702703;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3357487922705314,
                      y: constraints.maxHeight * 0.6621621621621622,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMenuWidget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.17632850241545894;

                final double height =
                    constraints.maxHeight * 0.2702702702702703;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.572463768115942,
                      y: constraints.maxHeight * 0.6621621621621622,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedHorarioWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.17632850241545894;

                final double height =
                    constraints.maxHeight * 0.2702702702702703;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.7995169082125604,
                      y: constraints.maxHeight * 0.6621621621621622,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPerfilWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.13043478260869565;

                final double height =
                    constraints.maxHeight * 0.6486486486486487;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.7777777777777778,
                      y: constraints.maxHeight * 0.05405405405405406,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeoplecircleoutlineWidget4(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
